packages:
  - packages/*
  - playground

catalog:
  '@changesets/cli': ^2.28.1
  husky: 9.1.7
  typescript: ^5.7.3
  unbuild: ^3.5.0
  vue: ^3.5.13
  '@commitlint/cli': ^20.2.0
  '@commitlint/config-conventional': ^20.2.0
  commitizen: ^4.3.1
  cz-conventional-changelog: ^3.3.0
